### ISSUE TITLE
Add HSTS header to fedrtc.org

### ISSUE THREAD

**Issue by tyll** [opentelecoms-org/fedrtc-org#1]
fedrtc.org is meant to be used only via HTTPS, therefore please set a HSTS header and add it to the HSTS preload list:
http://hstspreload.appspot.com/

**Comment by tyll** [comment]
ping?

**Comment by dpocock** [comment]
Thanks for this feedback.  We are discussing the possibility that it will become an official Fedora service under the fedoraproject.org domain and that may make this request redundant.  Can you comment on the urgency of this?

**Comment by tyll** [comment]
It needs to be done if it is migrated to Fedora as well:
https://fedorahosted.org/fedora-infrastructure/ticket/2888

It is also a rather simple change, but since the server config is not available I cannot provide a patch. For Apache httpd it would be a line like the following:

```
Header always add Strict-Transport-Security "max-age=15768000; includeSubDomains; preload"
```

It is not super urgent but urgent enough to do it if you have time/urgent enough to be done in 3 months. If you have any questions or need help, I will help you.

**Comment by dpocock** [comment]
Thanks for the feedback.  I've added that to the config file, can you please verify and then close the issue?

**Comment by tyll** [comment]
Thank you, it looks good. I also requested it to be added to the preload list.
